baseURL = 'https://jsian-chih.github.io/JSian.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
<<<<<<< HEAD
theme = 'ananke'

[[params.social]]
name = "email"
url = "mailto:jsian.chih@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/JSian-Chih"


=======
theme = 'ananke'
>>>>>>> 26419b2e378c17d21131e8856c5ff4f2b3d60e59
